# Generated by Django 5.2.8 on 2025-11-14 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'announcement',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('category', models.CharField(choices=[('Leave Policies', 'Leave Policies'), ('Payroll', 'Payroll'), ('Benefits', 'Benefits'), ('General', 'General')], default='General', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'faq',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Employee ID')),
                ('fname', models.CharField(max_length=50, verbose_name='First Name')),
                ('lname', models.CharField(max_length=50, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=100, verbose_name='Email Address')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone Number')),
                ('position', models.CharField(max_length=80)),
                ('dept', models.CharField(max_length=80, verbose_name='Department')),
                ('salary_grade', models.CharField(blank=True, max_length=20, verbose_name='Salary Grade')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('date_hired', models.DateField(blank=True, null=True)),
                ('civil_status', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Separated', 'Separated'), ('Widowed', 'Widowed')], max_length=20, null=True)),
                ('emp_status', models.CharField(choices=[('Regular', 'Regular'), ('Job Order', 'Job Order')], max_length=20, verbose_name='Employment Status')),
                ('address', models.CharField(blank=True, help_text='House/Lot no., Street Name', max_length=150, verbose_name='Street Address')),
                ('brgy', models.CharField(blank=True, max_length=80, verbose_name='Barangay')),
                ('city', models.CharField(blank=True, max_length=80, verbose_name='Municipality/City')),
                ('province', models.CharField(blank=True, max_length=80)),
                ('zipcode', models.CharField(blank=True, max_length=10)),
                ('emc_name', models.CharField(blank=True, max_length=100, verbose_name='Emergency Contact Name')),
                ('emc_relation', models.CharField(blank=True, max_length=50, verbose_name='Relationship')),
                ('emc_phone', models.CharField(blank=True, max_length=20, verbose_name='Emergency Contact Phone')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employee',
                'ordering': ['lname', 'fname'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_in', models.TimeField(blank=True, null=True)),
                ('time_out', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent'), ('fieldwork', 'Fieldwork'), ('health', 'Health-related')], default='present', max_length=20)),
                ('hours_worked', models.DecimalField(blank=True, decimal_places=2, help_text='Total hours worked (e.g. 7.50)', max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='accounts.employee')),
            ],
            options={
                'db_table': 'attendance_record',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('message_type', models.CharField(blank=True, max_length=50)),
                ('text', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('responded', 'Responded'), ('read', 'Read')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='accounts.employee')),
            ],
            options={
                'db_table': 'message',
                'ordering': ['-created_at'],
            },
        ),
    ]
