# Generated by Django 5.2.8 on 2025-11-14 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='must_change_password',
            field=models.BooleanField(default=True, help_text='If True, employee will be prompted to change their password on login.'),
        ),
    ]
