# Generated by Django 5.2.8 on 2025-11-14 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_employee_must_change_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='must_change_password',
        ),
    ]
