# Generated by Django 5.2.8 on 2025-11-15 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_employee_must_change_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_label', models.CharField(blank=True, max_length=100)),
                ('objective_name', models.CharField(max_length=200)),
                ('key_result_name', models.CharField(max_length=200)),
                ('progress_percent', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_records', to='accounts.employee')),
            ],
            options={
                'db_table': 'employee_performance',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyPerformanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('progress_percent', models.PositiveIntegerField(default=0)),
                ('activities_done', models.PositiveIntegerField(default=0)),
                ('total_activities', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_summaries', to='accounts.employee')),
            ],
            options={
                'db_table': 'weekly_performance_summary',
                'ordering': ['-week_start', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('is_done', models.BooleanField(default=False)),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='accounts.weeklyperformancesummary')),
            ],
            options={
                'db_table': 'weekly_activity',
                'ordering': ['id'],
            },
        ),
    ]
