# Generated by Django 5.2.8 on 2025-11-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_employeeperformance_weeklyperformancesummary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='jo_daily_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='sick_leave_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
