# Generated by Django 5.2.8 on 2026-02-08 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_salarygrade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salarygrade',
            old_name='monthly_amount',
            new_name='monthly_salary',
        ),
        migrations.RemoveField(
            model_name='salarygrade',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='salarygrade',
            name='updated_at',
        ),
    ]
