# Generated by Django 5.2.8 on 2026-02-09 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_monthly_amount_salarygrade_monthly_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='time_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='time_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
