# Generated by Django 5.2.8 on 2026-02-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_attendancerecord_time_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='time_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='time_out',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
