# Generated by Django 5.2.8 on 2026-02-14 02:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_qrsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrsession',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
