# Generated by Django 5.2.8 on 2026-02-14 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_monthly_amount_salarygrade_monthly_salary_and_more'),
        ('accounts', '0011_alter_qrsession_token'),
    ]

    operations = [
    ]
