# Generated by Django 5.2.8 on 2026-03-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_merge_20260214_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dept',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary_grade',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Salary Grade'),
        ),
    ]
