# Generated by Django 5.2.8 on 2026-04-15 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_employee_dept_alter_employee_position_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('VL', 'Vacation Leave'), ('SL', 'Sick Leave'), ('SPL', 'Special Privilege Leave'), ('WL', 'Wellness Leave'), ('PL', 'Paternity Leave'), ('ML', 'Maternity Leave'), ('SP', 'Solo Parent Leave'), ('EL', 'Emergency Leave')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('attachment', models.ImageField(blank=True, null=True, upload_to='leave_proofs/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('date_filed', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.employee')),
            ],
        ),
    ]
