# Generated by Django 5.2.8 on 2026-04-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_leaverequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent'), ('fieldwork', 'Fieldwork'), ('health', 'Health-related'), ('ON LEAVE', 'On Leave')], default='present', max_length=20),
        ),
    ]
