# Generated by Django 5.2.8 on 2026-04-20 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_attendancerecord_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
