

"""
Django settings for hris project.

Generated by 'django-admin startproject' using Django 5.2.8.
"""

from pathlib import Path
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent  # fixed: _file_ (not file)

# =========================================================
# CORE SECURITY / ENV SETTINGS
# =========================================================

# In production, set this via environment variable
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-9t7b+=_+$xd+=e&0gft+9grb_u0#kxn@91@9fpzno2ghbu28%4",
)

DEBUG = os.getenv("DJANGO_DEBUG", "True").lower() == "true"

ALLOWED_HOSTS_ENV = os.getenv("DJANGO_ALLOWED_HOSTS", "")
ALLOWED_HOSTS = [h for h in ALLOWED_HOSTS_ENV.split(",") if h]

CSRF_TRUSTED_ORIGINS_ENV = os.getenv("CSRF_TRUSTED_ORIGINS", "")
CSRF_TRUSTED_ORIGINS = [
    o for o in CSRF_TRUSTED_ORIGINS_ENV.split(",") if o
]

# =========================================================
# APPLICATIONS
# =========================================================

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "accounts",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # Whitenoise for serving static files in production
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "hris.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "hris.wsgi.application"
ASGI_APPLICATION = "hris.asgi.application"

# =========================================================
# DATABASE
# =========================================================

# Production: set DATABASE_URL in env (e.g. postgres://user:pass@host:5432/dbname)
# If DATABASE_URL is not set, it will fall back to your local PostgreSQL settings.
DATABASES = {
    "default": dj_database_url.config(
        default="postgres://postgres:112202@localhost:5432/HRIS",
        conn_max_age=600,
    )
}

# =========================================================
# PASSWORD VALIDATION
# =========================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# =========================================================
# INTERNATIONALIZATION
# =========================================================

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Manila"  # you can switch to "Asia/Manila" if you want

USE_I18N = True

USE_TZ = True

# =========================================================
# STATIC & MEDIA FILES
# =========================================================

# URL prefix for static files
STATIC_URL = "/static/"

# Folder where collectstatic will put all static files
STATIC_ROOT = BASE_DIR / "staticfiles"

# Whitenoise static file storage (for efficient serving in production)
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Media (if you ever start using file uploads)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# =========================================================
# DEFAULT PRIMARY KEY FIELD TYPE
# =========================================================

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"